name: templify
description: A dart command-line app to create modules or sub-modules using predefined templates.
repository: https://github.com/thisisprabhat/templify.git
homepage: https://github.com/thisisprabhat/templify.git

version: 0.8.2

environment:
  sdk: ^3.6.1

dependencies:
  args: ^2.6.0
  collection: ^1.19.1
  colored_log: ^1.2.0
  intl: ^0.20.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0


topics:
- cli
- template
- console

platforms:
  linux:
  android:
  ios:
  macos:
  web:
  windows:

executables:
  templify:
  
license: MIT
