name: templify
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

dependencies:
  args: ^2.6.0
  collection: ^1.19.1
  colored_log: ^1.2.0
  intl: ^0.20.2
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

